trigger:
  - azure
pool:
  vmImage: 'ubuntu-latest'
container:
  image: argosnotary/argosbuild-argos4j-cli
steps:
  - script: |
      postLink --phase pre --segment azure --step build --runId $BUILD_NUMBER
      mvn -q -s settings.xml clean install xldeploy:import -Drevision=$(Build.SourceVersion) -Dxldeploy.server=xldeploy.argosnotary.org -Dxldeploy.port=80
      postLink --phase post --segment azure --step build --runId $BUILD_NUMBER
    env:
      WORKSPACE: $(System.DefaultWorkingDirectory)
      BUILD_NUMBER: $(Build.BuildNumber)
      ARGOS_SERVICE_BASE_URL: https://notary.argosnotary.org/api
      CREDENTIALS_PASSPHRASE: $(credentials-pw)
      CREDENTIALS_KEY_ID: $(credentials-key-id)
      SUPPLY_CHAIN_NAME: argos-test-app
      SUPPLY_CHAIN_PATH: rabobank
    name: build
